import { rule as anarchicStyleSheetsMain } from "./anarchic_style_sheets/main";
import { rule as asciiArtMain } from "./ascii_art/main";
import { rule as backwardsCompatibilityMain } from "./backwards_compatibility/main";
import { rule as bigheadedMain } from "./bigheaded/main";
import { rule as bindPersonHaterMain } from "./bind_person_hater/main";
import { rule as bobRossMain } from "./bob_ross/main";
import { rule as bootstrapMain } from "./bootstrap/main";
import { rule as bulletHellMain } from "./bullet_hell/main";
import { rule as classWarfareMain } from "./class_warfare/main";
import { rule as classyBronze } from "./classy/bronze";
import { rule as classyGold } from "./classy/gold";
import { rule as classyPlatinum } from "./classy/platinum";
import { rule as classySilver } from "./classy/silver";
import { rule as commentatorInChiefMain } from "./commentator_in_chief/main";
import { rule as crossPlatformMain } from "./cross_platform/main";
import { rule as dataDrivenMain } from "./data_driven/main";
import { rule as dictionaryEnthusiastMain } from "./dictionary_enthusiast/main";
import { rule as divSoupBronze } from "./div_soup/bronze";
import { rule as divSoupGold } from "./div_soup/gold";
import { rule as divSoupPlatinum } from "./div_soup/platinum";
import { rule as divSoupSilver } from "./div_soup/silver";
import { rule as dynamicContentMain } from "./dynamic_content/main";
import { rule as emptyCaloriesMain } from "./empty_calories/main";
import { rule as faviconFanaticMain } from "./favicon_fanatic/main";
import { rule as flashbangGold } from "./flashbang/gold";
import { rule as flashbangPlatinum } from "./flashbang/platinum";
import { rule as formFanaticMain } from "./form_fanatic/main";
import { rule as frameworkPhobiaMain } from "./framework_phobia/main";
import { rule as htmxMain } from "./htmx/main";
import { rule as hydraMain } from "./hydra/main";
import { rule as hyperlinkCollectorBronze } from "./hyperlink_collector/bronze";
import { rule as hyperlinkCollectorGold } from "./hyperlink_collector/gold";
import { rule as hyperlinkCollectorPlatinum } from "./hyperlink_collector/platinum";
import { rule as hyperlinkCollectorSilver } from "./hyperlink_collector/silver";
import { rule as impaMain } from "./impa/main";
import { rule as importantPersonMain } from "./important_person/main";
import { rule as localityOfAppearanceMain } from "./locality_of_appearance/main";
import { rule as loremIpsumMain } from "./lorem_ipsum/main";
import { rule as masterOfElementsBronze } from "./master_of_elements/bronze";
import { rule as masterOfElementsGold } from "./master_of_elements/gold";
import { rule as masterOfElementsPlatinum } from "./master_of_elements/platinum";
import { rule as masterOfElementsSilver } from "./master_of_elements/silver";
import { rule as millionthVisitorMain } from "./millionth_visitor/main";
import { rule as okBoomerMain } from "./ok_boomer/main";
import { rule as oopsAllFrameworksMain } from "./oops_all_frameworks/main";
import { rule as phdPuristMain } from "./phd_purist/main";
import { rule as preemptiveStrikeMain } from "./preemptive_strike/main";
import { rule as progressiveMain } from "./progressive/main";
import { rule as quirkyMain } from "./quirky/main";
import { rule as regressiveEnhancementMain } from "./regressive_enhancement/main";
import { rule as scriptoniteGold } from "./scriptonite/gold";
import { rule as scriptonitePlatinum } from "./scriptonite/platinum";
import { rule as scriptoniteSilver } from "./scriptonite/silver";
import { rule as selfLoveMain } from "./self_love/main";
import { rule as semanticSnobGold } from "./semantic_snob/gold";
import { rule as semanticSnobPlatinum } from "./semantic_snob/platinum";
import { rule as seoSleazeballMain } from "./seo_sleazeball/main";
import { rule as slotMachineMain } from "./slot_machine/main";
import { rule as smallDataMain } from "./small_data/main";
import { rule as soapBoxMain } from "./soap_box/main";
import { rule as testInProdMain } from "./test_in_prod/main";
import { rule as todoBronze } from "./todo/bronze";
import { rule as todoGold } from "./todo/gold";
import { rule as todoSilver } from "./todo/silver";
import { rule as tooMetaMain } from "./too_meta/main";
import { rule as towerOfBabelMain } from "./tower_of_babel/main";
import { rule as treeShenanigansDeepPuddle } from "./tree_shenanigans/deep_puddle";
import { rule as treeShenanigansShallowOcean } from "./tree_shenanigans/shallow_ocean";
import { rule as typeHintsNaturalLanguageStaticTyping } from "./type_hints/natural_language_static_typing";
import { rule as typeHintsTypeHints } from "./type_hints/type_hints";
import { rule as vintageMain } from "./vintage/main";
import { rule as voidElementsCloseMinded } from "./void_elements/close_minded";
import { rule as voidElementsDoubleMinded } from "./void_elements/double_minded";
import { rule as voidElementsOpenMinded } from "./void_elements/open_minded";
import { rule as weDoThingsALittleDifferentMain } from "./we_do_things_a_little_different/main";
import { rule as web10CertifiedMain } from "./web_1_0_certified/main";
import { rule as youAreAmazingEmbedMain } from "./you_are_amazing_embed/main";
import { rule as youtubeJunkieMain } from "./youtube_junkie/main";
import { rule as zalgoMain } from "./zalgo/main";

import { createAchievementRegistry } from "./registry";
export { achievementIds } from "./types";
export type {
  AchievementContext,
  AchievementHierarchy,
  AchievementId,
  AchievementRule,
} from "./types";

const registry = createAchievementRegistry();

registry.register(anarchicStyleSheetsMain);
registry.register(asciiArtMain);
registry.register(backwardsCompatibilityMain);
registry.register(bigheadedMain);
registry.register(bindPersonHaterMain);
registry.register(bobRossMain);
registry.register(bootstrapMain);
registry.register(bulletHellMain);
registry.register(classWarfareMain);
registry.register(classyBronze);
registry.register(classyGold);
registry.register(classyPlatinum);
registry.register(classySilver);
registry.register(commentatorInChiefMain);
registry.register(crossPlatformMain);
registry.register(dataDrivenMain);
registry.register(dictionaryEnthusiastMain);
registry.register(divSoupBronze);
registry.register(divSoupGold);
registry.register(divSoupPlatinum);
registry.register(divSoupSilver);
registry.register(dynamicContentMain);
registry.register(emptyCaloriesMain);
registry.register(faviconFanaticMain);
registry.register(flashbangGold);
registry.register(flashbangPlatinum);
registry.register(formFanaticMain);
registry.register(frameworkPhobiaMain);
registry.register(htmxMain);
registry.register(hydraMain);
registry.register(hyperlinkCollectorBronze);
registry.register(hyperlinkCollectorGold);
registry.register(hyperlinkCollectorPlatinum);
registry.register(hyperlinkCollectorSilver);
registry.register(impaMain);
registry.register(importantPersonMain);
registry.register(localityOfAppearanceMain);
registry.register(loremIpsumMain);
registry.register(masterOfElementsBronze);
registry.register(masterOfElementsGold);
registry.register(masterOfElementsPlatinum);
registry.register(masterOfElementsSilver);
registry.register(millionthVisitorMain);
registry.register(okBoomerMain);
registry.register(oopsAllFrameworksMain);
registry.register(phdPuristMain);
registry.register(preemptiveStrikeMain);
registry.register(progressiveMain);
registry.register(quirkyMain);
registry.register(regressiveEnhancementMain);
registry.register(scriptoniteGold);
registry.register(scriptonitePlatinum);
registry.register(scriptoniteSilver);
registry.register(selfLoveMain);
registry.register(semanticSnobGold);
registry.register(semanticSnobPlatinum);
registry.register(seoSleazeballMain);
registry.register(slotMachineMain);
registry.register(smallDataMain);
registry.register(soapBoxMain);
registry.register(testInProdMain);
registry.register(todoBronze);
registry.register(todoGold);
registry.register(todoSilver);
registry.register(tooMetaMain);
registry.register(towerOfBabelMain);
registry.register(treeShenanigansDeepPuddle);
registry.register(treeShenanigansShallowOcean);
registry.register(typeHintsNaturalLanguageStaticTyping);
registry.register(typeHintsTypeHints);
registry.register(vintageMain);
registry.register(voidElementsCloseMinded);
registry.register(voidElementsDoubleMinded);
registry.register(voidElementsOpenMinded);
registry.register(weDoThingsALittleDifferentMain);
registry.register(web10CertifiedMain);
registry.register(youAreAmazingEmbedMain);
registry.register(youtubeJunkieMain);
registry.register(zalgoMain);

export const rulesById = registry.rulesById;
export const rules = registry.rules;
